import Image from "next/image";
import Head from "next/head";
import { IoLogoYoutube } from "react-icons/io";
import { FaLinkedin } from "react-icons/fa";
import { AiFillTwitterCircle } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import ServiseCard from "@/components/ServiseCard";
import Nav from "@/components/Nav";
import DeveloperDetails from "@/components/DeveloperDetails";
import PortfolioItem from "@/components/PortfolioItem";
import { useState } from "react";


const serivces = [
  {
    title: "Beautiful Designs",
    imageSrc:"/static/glare-isometric-hashtag.png",
    explination:
      "Creating elegant designs suited for your needs following core design theory",
    toolsTitle:"Design Tools I Use",
    tools:["Photoshop" , "ILLustrato" , "Figma" , "Indesign"]
  },
  {
    title: "Code your dream project",
    imageSrc:"/static/icons8-design-48.png",
    explination:
      "Do you have an idea for your next great website? Let's make it a reality.",
    toolsTitle:"Design Tools I Use",
    tools:["Photoshop" , "ILLustrato" , "Figma" , "Indesign"]
  },
  {
    title: "Consulting",
    imageSrc:"/static/icons8-facebook-like-48.png",
    explination:
      "Are you interested feedback for your current project? I can give you tips and tricks to level it up.",
    toolsTitle:"Design Tools I Use",
    tools:["Photoshop" , "ILLustrato" , "Figma" , "Indesign"]
  },
];

const portfolioItems =[ 
  "/static/banner-redimensionat.jpg",
  "/static/best-photography-portfolio-website-examples-1024x514.webp",
  "/static/e0d7fe178013497.Y3JvcCw0MDQwLDMxNjAsMCww.png",
  "/static/1_FSw05BlhE8exLYeHAmQa9g.png"
]

export default function Home() {
  const [theme, setTheme] = useState(false);
  const themChangeHandler = ()=>{ 
    setTheme((state)=>!state);
  }
  return (
    <div>
      {/* <Head> 
          <title>Dimitri Marco Portfolio</title>
          <meta name="description" content="Generated by M7md"> 
            <link rel="icon" href="/favicon.ico" />
          </meta>
        </Head> */}
      <main className={`px-[10%] pt-[20px] ${theme?"text-black bg-white":"text-white bg-slate-800"}`}>
        <section className="min-h-screen">
          <Nav theme={theme} onClick={themChangeHandler}/>
          <DeveloperDetails/>
        
          <div className="my-20 ">
            <h1 className=" my-10 text-3xl font-medium">Services I Offer</h1>
            <p className="leading-8">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for{" "}
              <span className="text-teal-600">agencies</span> consulted for
              <span className="text-teal-600"> startups</span> and collaborated
              with talanted people to create digital products for both business
              and consumer use.
            </p>
            <p className="my-10">
              I offer from a wide range of services, including brand design,
              programming and teaching
            </p>
          </div>
          {/* Start of Services Department */}
          <div className="flex flex-col lg:flex-row gap-10">
            { 
            serivces.map(ele => <ServiseCard key={ele.title} service={ele}/> )}
          </div>
          {/* End of Services Department */}

          {/* Start of Portfolio Department */}
          <div  className="my-20 ">
            <h1 className="my-10 text-3xl font-medium">Portofolio</h1>
            <p className="leading-8">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for{" "}
              <span className="text-teal-600">agencies</span> consulted for
              <span className="text-teal-600"> startups</span> and collaborated
              with talanted people to create digital products for both business
              and consumer use.
            </p>
            <p className="my-10">
              I offer from a wide range of services, including brand design,
              programming and teaching
            </p>
          </div>
          {/* End of portfolio Department */}
          <div className="flex flex-col justify-between py-20   lg:flex-row flex-wrap gap-10 "> 
            { 
            portfolioItems.map(ele => <PortfolioItem key={ele} src={ele}/>
              )
            }
          </div>
        </section>
      </main>
    </div>
  );
}
